source "https://rubygems.org"

# gem "fastlane"

# TEMPORARY SOLUTION
# https://github.com/fastlane/fastlane/issues/14521
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz-pilot-fixes-removed-build-trains"
