# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  match(
        type: "development",
        git_url: "git@github.com:paul-barry-kenzan/signing-keys.git"
      )
    increment_build_number(xcodeproj: "mobilePrototype.xcodeproj")
    build_app(
      scheme: "mobilePrototype",
      export_method: "development",
      export_options: {
        provisioningProfiles: {
          "com.example.mobilePrototypeCiCd" => "match Development com.kenzan.mobilePrototypeCiCd"
        }
      }
    )
    upload_to_testflight
  end
end
