# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  lane :beta do
    match(
      type: "development",
      git_url: "git@github.com:paul-barry-kenzan/signing-keys.git"
    )

    increment_build_number(xcodeproj: "mobileCiCdApp.xcodeproj")
    build_app(scheme: "mobileCiCdApp")
    upload_to_testflight
  end

end
